# Generated by Django 3.1 on 2020-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=64)),
                ('item_size', models.CharField(blank=True, max_length=64, null=True)),
                ('no_topping', models.IntegerField(blank=True, default=0, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
