# Generated by Django 3.1 on 2020-09-02 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200902_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='toppings_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_1', to='menu.toppings'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='toppings_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_2', to='menu.toppings'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='toppings_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_3', to='menu.toppings'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='toppings_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_4', to='menu.toppings'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='toppings_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_5', to='menu.toppings'),
        ),
    ]
